### ISSUE TITLE
validate_install.py Error:  missing 1 required keyword-only argument: 'accomplishment_fns'

### ISSUE THREAD

**Issue by hxsnow10** [CraftJarvis/MC-Simulator#3]
hello， it seems this script(task_id="combat_spider_plains_leather_armors_diamond_sword_shield") doesn't work.
task_id="harvest_wool_with_shears_and_sheep"  is OK.

```
[root] MC-Simulator# xvfb-run python scripts/validate_install.py
Traceback (most recent call last):
  File "/root/Codes/MC-Simulator/scripts/validate_install.py", line 5, in <module>
    env = minedojo.make(
  File "/root/Codes/MC-Simulator/minedojo/tasks/__init__.py", line 520, in make
    env_obj = _specific_task_make(task_id, *args, **kwargs)
  File "/root/Codes/MC-Simulator/minedojo/tasks/__init__.py", line 496, in _specific_task_make
    task_obj = _meta_task_make(meta_task_cls, *args, **task_specs, **kwargs)
  File "/root/Codes/MC-Simulator/minedojo/tasks/__init__.py", line 82, in _meta_task_make
    return MetaTaskName2Class[meta_task](*args, **kwargs)
  File "/root/Codes/MC-Simulator/minedojo/tasks/meta/combat.py", line 227, in __init__
    super().__init__(
TypeError: ExtraSpawnMetaTaskBase.__init__() missing 1 required keyword-only argument: 'accomplishment_fns'
```

**Comment by Curious-L** [comment]
请问一下，还是报错，显示这种结果，不太理解：
```
  multiarray.copyto(a, fill_value, casting='unsafe')
[INFO] Create a task with prompt: shear a sheep with shears and a sheep nearby
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 1/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 2/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 3/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 4/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 5/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 6/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 7/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 8/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 9/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 10/10.This is probably an intermittent race condition. Trying again (max tries 10).
```
