### ISSUE TITLE
`python minedojo/scripts/validate_install.py`报错

### ISSUE THREAD

**Issue by Curious-L** [CraftJarvis/MC-Simulator#4]
安装验证报错：
```
[INFO] Create a task with prompt: shear a sheep with shears and a sheep nearby
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 1/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 2/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 3/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 4/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 5/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 6/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 7/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 8/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 9/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Minecraft build or launch just failed on attempt 10/10.This is probably an intermittent race condition. Trying again (max tries 10).
```

**Comment by alset0326** [comment]
try this
first, fix mixingradle
```diff
diff --git a/minedojo/sim/Malmo/Minecraft/build.gradle b/minedojo/sim/Malmo/Mine
craft/build.gradle
index e585c14..4ad2d7a 100755
--- a/minedojo/sim/Malmo/Minecraft/build.gradle
+++ b/minedojo/sim/Malmo/Minecraft/build.gradle
@@ -13,10 +13,12 @@ buildscript {
             name = "sonatype"
             url = "https://oss.sonatype.org/content/repositories/snapshots/"
         }
+        maven { url 'https://repo.spongepowered.org/repository/maven-public/' }
     }
     dependencies {
         classpath 'org.ow2.asm:asm:6.0'
-        classpath('com.github.SpongePowered:MixinGradle:dcfaf61'){ // 0.6
+        classpath('org.spongepowered:mixingradle:0.6-SNAPSHOT'){ // 0.6
             // Because forgegradle requires 6.0 (not -debug-all) while mixingradle depends on 5.0
             // and putting mixin right here will place it before forge in the class loader
             exclude group: 'org.ow2.asm', module: 'asm-debug-all'
```
then, fix assets err
```bash
cd $HOME/.gradle/caches/minecraft/assets
grep -e '[a-zA-Z0-9]\{40\}' -o indexes/*.json | awk '{ print substr($0,0,2)"/"$0}' | xargs -n 1 -I '{}' curl 'https://resources.download.minecraft.net/{}' -o 'objects/{}'
```

**Comment by Cu2ta1n** [comment]
I seem to encouter the same error, would you give me more specific solution ? @alset0326 

`(minedojo1) ouc_zmy@ouc-SYS-4029GP-TRT:/home/ouc/data2/zmy/MC-Simulator$ python scripts/validate_install.py

[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Making meta task combat, args: (), kwargs: {'target_names': 'spider', 'target_quantities': 1, 'reward_weights': 1, 'initial_mobs': 'spider', 'initial_mob_spawn_range_low': [-7, 1, -7], 'initial_mob_spawn_range_high': [7, 1, 7], 'start_at_night': True, 'always_night': True, 'specified_biome': 'plains', 'allow_mob_spawn': False, 'use_voxel': True, 'voxel_size': {'xmin': -1, 'ymin': -1, 'zmin': -1, 'xmax': 1, 'ymax': 1, 'zmax': 1}, 'use_lidar': False, 'image_size': (288, 512), 'world_seed': 123, 'seed': 42, 'initial_inventory': [InventoryItem(slot='mainhand', name='diamond_sword', variant=None, quantity=None), InventoryItem(slot='feet', name='leather_boots', variant=None, quantity=None), InventoryItem(slot='legs', name='leather_leggings', variant=None, quantity=None), InventoryItem(slot='chest', name='leather_chestplate', variant=None, quantity=None), InventoryItem(slot='head', name='leather_helmet', variant=None, quantity=None), InventoryItem(slot='offhand', name='shield', variant=None, quantity=None)]}
[INFO] Using fast reset with teleport range: 100
/home/ouc/anaconda3/envs/minedojo1/lib/python3.9/site-packages/gym/spaces/box.py:78: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
[INFO] Create a task with prompt: combat a spider in night plains with a diamond sword, shield, and a full suite of leather armors
>>>>>> Launching a Malmo instance with online mode <<<<<<
Minecraft build or launch just failed on attempt 1/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
Minecraft build or launch just failed on attempt 2/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
Minecraft build or launch just failed on attempt 3/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
Minecraft build or launch just failed on attempt 4/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
Minecraft build or launch just failed on attempt 5/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
Minecraft build or launch just failed on attempt 6/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
Minecraft build or launch just failed on attempt 7/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
Minecraft build or launch just failed on attempt 8/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
Minecraft build or launch just failed on attempt 9/10.This is probably an intermittent race condition. Trying again (max tries 10).
>>>>>> Launching a Malmo instance with online mode <<<<<<
Minecraft build or launch just failed on attempt 10/10.This is probably an intermittent race condition. Trying again (max tries 10).
Traceback (most recent call last):
  File "/home/ouc/data2/zmy/MC-Simulator/scripts/validate_install.py", line 14, in <module>
    env.reset()
  File "/home/ouc/anaconda3/envs/minedojo1/lib/python3.9/site-packages/gym/core.py", line 283, in reset
    return self.env.reset(**kwargs)
  File "/home/ouc/data2/zmy/MC-Simulator/minedojo/sim/wrappers/ar_nn/delta_inventory_wrapper.py", line 79, in reset
    observation = self.env.reset(**kwargs)
  File "/home/ouc/anaconda3/envs/minedojo1/lib/python3.9/site-packages/gym/core.py", line 311, in reset
    return self.observation(self.env.reset(**kwargs))
  File "/home/ouc/data2/zmy/MC-Simulator/minedojo/sim/wrappers/ar_nn/nn_action_space_wrapper.py", line 373, in reset
    obs = self.env.reset(**kwargs)
  File "/home/ouc/data2/zmy/MC-Simulator/minedojo/tasks/meta/base.py", line 123, in reset
    obs = self.env.reset(**kwargs)
  File "/home/ouc/data2/zmy/MC-Simulator/minedojo/sim/wrappers/fast_reset.py", line 110, in reset
    obs = self.env.reset(**kwargs)
  File "/home/ouc/data2/zmy/MC-Simulator/minedojo/sim/sim.py", line 423, in reset
    raw_obs = self._bridge_env.reset(episode_id, [xml])[0]
  File "/home/ouc/data2/zmy/MC-Simulator/minedojo/sim/bridge/bridge_env/bridge_env.py", line 71, in reset
    self._setup_instances()
  File "/home/ouc/data2/zmy/MC-Simulator/minedojo/sim/bridge/bridge_env/bridge_env.py", line 168, in _setup_instances
    self._instances.extend([f.result() for f in instance_futures])
  File "/home/ouc/data2/zmy/MC-Simulator/minedojo/sim/bridge/bridge_env/bridge_env.py", line 168, in <listcomp>
    self._instances.extend([f.result() for f in instance_futures])
  File "/home/ouc/anaconda3/envs/minedojo1/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/ouc/anaconda3/envs/minedojo1/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/ouc/anaconda3/envs/minedojo1/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ouc/data2/zmy/MC-Simulator/minedojo/sim/bridge/bridge_env/bridge_env.py", line 219, in _robust_get_new_instance
    raise RuntimeError(f"Failed to build and launch Minecraft instance "
RuntimeError: Failed to build and launch Minecraft instance 10 times. Giving up.
`

**Comment by alset0326** [comment]
Have you tried my fix? @Cu2ta1n

**Comment by Cu2ta1n** [comment]
@alset0326 Thanks for your response !!!Yes I have tried your fix, but I don't have the dir `.gradle/caches/minecraft/assetsas`, so I ignore the 
`cd $HOME/.gradle/caches/minecraft/assets
grep -e '[a-zA-Z0-9]\{40\}' -o indexes/*.json | awk '{ print substr($0,0,2)"/"$0}' | xargs -n 1 -I '{}' curl 'https://resources.download.minecraft.net/{}' -o 'objects/{}'`
 as I undersand, I modify the `build.gradle` in `/home/ouc/data2/zmy/MC-Simulator/minedojo/sim/Malmo/Minecraft/ `, but it doesn't work

` buildscript {
    repositories {

        maven { url 'https://jitpack.io' }
        jcenter()
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net/"
        }
        maven {
            name = "sonatype"
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
        }
        maven { url 'https://repo.spongepowered.org/repository/maven-public/' }
    }
    dependencies {
        classpath 'org.ow2.asm:asm:6.0'
        classpath('org.spongepowered:mixingradle:0.6-SNAPSHOT'){ // 0.6
             // Because forgegradle requires 6.0 (not -debug-all) while mixingradle depends on 5.0
             // and putting mixin right here will place it before forge in the class loader
             exclude group: 'org.ow2.asm', module: 'asm-debug-all'
        classpath files("${projectDir}/libs/MixinGradle-dcfaf61.jar")

        classpath 'com.github.brandonhoughton:ForgeGradle:FG_2.2_patched-SNAPSHOT'
    }buildscript {
    repositories {

        maven { url 'https://jitpack.io' }
        jcenter()
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net/"
        }
        maven {
            name = "sonatype"
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
        }
        maven { url 'https://repo.spongepowered.org/repository/maven-public/' }
    }
    dependencies {
        classpath 'org.ow2.asm:asm:6.0'
        classpath('org.spongepowered:mixingradle:0.6-SNAPSHOT'){ // 0.6
             // Because forgegradle requires 6.0 (not -debug-all) while mixingradle depends on 5.0
             // and putting mixin right here will place it before forge in the class loader
             exclude group: 'org.ow2.asm', module: 'asm-debug-all'
        classpath files("${projectDir}/libs/MixinGradle-dcfaf61.jar")

        classpath 'com.github.brandonhoughton:ForgeGradle:FG_2.2_patched-SNAPSHOT'
    }`

**Comment by alset0326** [comment]
I think the dir is now exists, check it around.  @Cu2ta1n

**Comment by Cu2ta1n** [comment]
Sorry, I still cannot find the dir
`ouc_zmy@ouc-SYS-4029GP-TRT:/home/ouc/data2/zmy/.gradle/caches/minecraft$ ls
de           McManifest.json       McpMappings.json       net
deobfedDeps  McManifest.json.etag  McpMappings.json.etag  versionJsons`
Maybe other things result the problem? like internet, my server cannot connect some website like github.

**Comment by alset0326** [comment]
Try these commands and see if the dir would exists. @Cu2ta1n 

```bash
cd minedojo/sim/Malmo/Minecraft/
./gradlew runClient
```
